fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Rauchzeit', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['ian@wreg.gs', 'sean.wreg@gmail.com', 'domosan@gmail.com', 'Anderson3510@gmail.com', 'jabarker1@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '7dee18ac0ff6fefd4a1efc2a3cb3eed76989cd87',
             build_secret: 'ae424e6da49cd223becd901e6970bdb0c00e8b3b45a5f9c19e1bd8076f3874ee',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
